# Generated by Django 5.0.2 on 2024-02-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domainURL", models.URLField()),
                ("domainTitle", models.CharField(max_length=255)),
                ("timeAccessed", models.CharField(max_length=255)),
                ("domainRating", models.PositiveIntegerField(default=0)),
                ("reasonNoHttps", models.BooleanField(default=False)),
                ("reasonShortened", models.BooleanField(default=False)),
                ("reasonAtSymbol", models.BooleanField(default=False)),
                ("reasonBadExtension", models.BooleanField(default=False)),
                ("clicked_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
